// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/tm-ox/go-datastar/views/modules"
)

func BaseLayout(items []modules.NavItem, currentPath string, meta modules.Meta, cartTotal int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = modules.SEO(meta).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<link rel=\"stylesheet\" href=\"/static/app.css\"><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@v1/bundles/datastar.js\"></script></head><body data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("{cartTotal: %d, menuOpen: false, drawerOpen: false, lightboxOpen: false, lightboxIndex: 0, lightboxImages: [], lightboxSrc: '', lightboxAlt: ''}", cartTotal))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layouts/base.templ`, Line: 20, Col: 188}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-on:keydown__window=\"evt.key === 'Escape' && ($drawerOpen = false, $lightboxOpen = false); evt.key === 'ArrowRight' && $lightboxOpen && ($lightboxIndex = ($lightboxIndex + 1) % $lightboxImages.length, $lightboxSrc = $lightboxImages[$lightboxIndex]); evt.key === 'ArrowLeft' && $lightboxOpen && ($lightboxIndex = ($lightboxIndex - 1 + $lightboxImages.length) % $lightboxImages.length, $lightboxSrc = $lightboxImages[$lightboxIndex])\"><header id=\"site-header\" style=\"view-transition-name: site-header\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = modules.Navbar(items, currentPath).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</header><main id=\"main\" style=\"view-transition-name: main-content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = modules.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div data-show=\"$drawerOpen\" data-on:click=\"$drawerOpen = false\" class=\"fixed inset-0 z-40 bg-black/50\"></div><div id=\"cart-drawer\" data-class='{\"translate-x-full\": !$drawerOpen}' class=\"fixed right-0 top-16 h-full w-96 z-50 bg-surface rounded-l-lg border-l border-y border-border transition-transform duration-300 translate-x-full\"></div><div id=\"lightbox\" class=\"fixed inset-0 z-50\" style=\"display:none\" data-show=\"$lightboxOpen\"><div class=\"absolute inset-0 bg-black/80\" data-on:click=\"$lightboxOpen = false\"></div><div class=\"absolute inset-0 flex items-center justify-center pointer-events-none\"><img data-attr:src=\"$lightboxSrc\" data-attr:alt=\"$lightboxAlt\" class=\"h-fit max-h-2/3 max-w-[90%] md:max-w-2/3 object-contain bg-canvas border border-border rounded-lg pointer-events-auto\"></div><button class=\"absolute left-2 md:left-16 top-[90%] md;top-1/2 -translate-y-1/2 text-muted text-6xl hover:text-accent cursor-pointer\" data-on:click=\"$lightboxIndex = ($lightboxIndex - 1 + $lightboxImages.length) % $lightboxImages.length; $lightboxSrc = $lightboxImages[$lightboxIndex]\">&#8592;</button> <button class=\"absolute right-2 md:right-16 top-[90%] md;top-1/2 -translate-y-1/2 text-muted text-6xl hover:text-accent cursor-pointer\" data-on:click=\"$lightboxIndex = ($lightboxIndex + 1) % $lightboxImages.length; $lightboxSrc = $lightboxImages[$lightboxIndex]\">&#8594;</button></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
